version: '3'
services:
    main:
        build: .
        volumes:
            - .:/home/node/sample1
        ports:
            - '3000:3000'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            HOST_IP: ${HOST_IP}
        depends_on:
            - registrator
        command: npm run dev

    registrator:
        image: gliderlabs/registrator
        command: consul://consul:8500
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        depends_on:
            - consul

    mongo:
        image: mongo
        depends_on:
            - registrator
        ports:
            - '27017:27017'
            - '27018:27018'

    consul:
        image: consul:latest
        ports:
            - '8400:8400'
            - '8500:8500'
            - '8600:53/udp'
        labels:
            SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
        command: [agent, '-server', '-ui', '-bootstrap', '-client=0.0.0.0']
